---
title: Bruh :3
---
classDiagram

    class `Road`{
        - String name
        - float speedLimit
        - float length
        - Lane[] lanes
        - float normalX
        - float normalY
        - long tick

        # Road(String name, int lanes, Intersection from, Intersection to)
        + void addLanes(int numNew)
        + void tick(Simulation sim, float delta)
        + void changedPosition(RoadMap map)
        + void changedPosition(Intersection start, Intersection end)
        + float getNormalX()
        + float getNormalY()
        + void draw(Simulation sim, RoadMap map)
        + String getName()
        + float getSpeedLimit()
        + void setSpeedLimit(float speedLimit)
        + float getSpace(int lane)
        + Lane getLane(int lane)
        + int getNumLanes()
        + Lane[] getLanes()
        + float getLength()
    }

    namespace test {
        class test2
    }


    class `Road.Surroundings`{
        Vehicle leftFront
        double leftSpaceToFront
        Vehicle leftBack
        double leftSpaceToBack
        Lane left
        Lane current
        Vehicle front
        double spaceToFront
        Vehicle back
        double spaceToBack
        Lane right
        Vehicle rightFront
        double rightSpaceToFront
        Vehicle rightBack
        double rightSpaceToBack

    }

    class `Road.LaneChangeDecision`{
        <<enumeration>>
        ForceLeft
        NudgeLeft
        WaitLeft
        Nothing
        WaitRight
        NudgeRight
        ForceRight

        boolean nudge
        boolean force
        int laneOffset

        LaneChangeDecision(boolean nudge, boolean force, int laneOffset)
    }

    class `Road.Lane`{
        - int lane
        - float remainingSpace
        - ArrayList#60;Vehicle#62; vehicles
        + boolean leftmost
        + boolean rightmost

        - Lane(int lane, boolean leftmost, boolean rightmost)
        + Road road()
        + Vehicle removeEnd()
        + boolean canFit(Vehicle vehicle)
        + void addVehicle(Vehicle vehicle)
        + float remainingSpace()
        + int getLane()
    }

